### ISSUE TITLE
info messages logged as warnings

### ISSUE THREAD

**Issue by davidgilbertson** [huggingface/datasets#5444] opened 2023-01-20 01:19 UTC
### Describe the bug

Code in `datasets` is using `logger.warning` when it should be using `logger.info`.

Some of these are probably a matter of opinion, but I think anything starting with `logger.warning(f"Loading chached` clearly falls into the info category.

Definitions from the Python docs for reference:
* INFO: Confirmation that things are working as expected.
* WARNING: An indication that something unexpected happened, or indicative of some problem in the near future (e.g. ‘disk space low’). The software is still working as expected.

In theory, a user should be able to resolve things such that there are no warnings.

### Steps to reproduce the bug

Load any dataset that's already cached.

### Expected behavior

No output when log level is at the default WARNING level.

### Environment info

- `datasets` version: 2.8.0
- Platform: Linux-5.10.102.1-microsoft-standard-WSL2-x86_64-with-glibc2.31
- Python version: 3.10.8
- PyArrow version: 9.0.0
- Pandas version: 1.5.2

**Comment by mariosasko** [comment] 2023-01-20 18:13
Looks like a duplicate of https://github.com/huggingface/datasets/issues/1948. 

I also think these should be logged as INFO messages, but let's see what @lhoestq thinks.

**Comment by lhoestq** [comment] 2023-01-23 09:57
It can be considered unexpected to see a `map` function return instantaneously. The warning is here to explain this case by mentioning that the cache was used. I don't expect first time users (only seeing warnings) to guess that the cache works this way

**Comment by davidgilbertson** [comment] 2023-01-23 23:07
Oh, so it's intentional? Do all Hugging Face packages use `warning` when using cache?
I guess feel free to close this issue then.

**Comment by lhoestq** [comment] 2023-01-24 11:20
Yes it's intentional for `map`. For `load_dataset` it's also intentional but for a different reason: it shows where in the cache the dataset is located, in case the user wants to clear the cache.

**Comment by davidgilbertson** [comment] 2023-01-24 22:07
OK I see. It's surprising to me that these are considered "something unexpected happened", the concept of cache is pretty common.

Has a user every actually complained that they ran their code once, and it took a minute while the data downloaded, then ran their code again and it ran really fast (and completed successfully) but they were so baffled by the fact that it ran quickly, _and_ didn't set the log level to INFO, _and_ hadn't read the docs (or thought about it) to know that datasets are cached, that they logged an issue asking that this information be output as a warning every time they run their code?

That seems like a very niche scenario to cater for, given that the side effect is to flood the console with irrelevant warnings for every other user every other time they run a bit of `datasets` code. And the real world impact is that people TURN OFF warnings, which is a pretty bad habit to get into.

Anyhoo, if there's no chance I'm going to change your mind, please close the issue :)

**Comment by lhoestq** [comment] 2023-01-25 15:43
I see your point and I'm not closed to switching to INFO, but I think those logs are important to make the library less opaque. I also just checked `transformers` scripts and they default to INFO which is nice. However for colab users the default is still WARNING iirc, and it counts as one of the main env where `datasets` is used.

We also use progress bars a lot in `datasets`, that are shown if the logger is at the WARNING level. But we offer a function to disable the progress bars if necessary.

**Comment by mariosasko** [comment] 2023-04-17 15:39
These kinds of messages are logged as INFO in Transformers, so we should probably be consistent with them

**Closed** 2023-07-12 17:19 UTC
