### ISSUE TITLE
Dataset viewer issue for Winoground

### ISSUE THREAD

**Issue by alcinos** [huggingface/datasets#4139] opened 2022-04-11 06:11 UTC
## Dataset viewer issue for 'Winoground'

**Link:** [*link to the dataset viewer page*](https://huggingface.co/datasets/facebook/winoground/viewer/facebook--winoground/train)

*short description of the issue*
Getting 401, message='Unauthorized'
The dataset is subject to authorization, but I can access the files from the interface, so I assume I'm granted to access it. I'd assume the permission somehow doesn't propagate to the dataset viewer tool.

Am I the one who added this dataset ? No

**Comment by odellus** [comment] 2022-04-12 07:39
I'm getting an error when I `load_dataset('facebook/winoground', use_auth_token=tok)`. Looks like there's some ISO-8859-1 encoding in the JSON for winograd's dataset.
```
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte
```
Probably related to why the dataset viewer isn't working.

**Comment by severo** [comment] 2022-04-12 08:22
related (same dataset): https://github.com/huggingface/datasets/issues/4149. But the issue is different. Looking at it

**Comment by odellus** [comment] 2022-04-12 09:43
I thought this issue was related to the error I was seeing, but upon consideration I'd think the dataset viewer would return a 500 (unable to create the split like me) or a 404 (unable to load split b/c it was never created) error if it was having the issue I was seeing in #4149. 401 message makes it look like dataset viewer isn't passing through the identity of the user who has signed the licensing agreement when making the request to GET [examples.jsonl](https://huggingface.co/datasets/facebook/winoground/resolve/a86a60456fbbd242e9a744199071a6bd3e7fd9de/examples.jsonl).

**Comment by severo** [comment] 2022-04-12 14:24
To replicate:

```python
>>> import datasets
>>> dataset= datasets.load_dataset('facebook/winoground', name='facebook--winoground', split='train', streaming=True, use_token="hf_app_...")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/slesage/hf/datasets-preview-backend/.venv/lib/python3.9/site-packages/datasets/load.py", line 1660, in load_dataset
    builder_instance = load_dataset_builder(
  File "/home/slesage/hf/datasets-preview-backend/.venv/lib/python3.9/site-packages/datasets/load.py", line 1486, in load_dataset_builder
    dataset_module = dataset_module_factory(
  File "/home/slesage/hf/datasets-preview-backend/.venv/lib/python3.9/site-packages/datasets/load.py", line 1238, in dataset_module_factory
    raise e1 from None
  File "/home/slesage/hf/datasets-preview-backend/.venv/lib/python3.9/site-packages/datasets/load.py", line 1209, in dataset_module_factory
    raise e
  File "/home/slesage/hf/datasets-preview-backend/.venv/lib/python3.9/site-packages/datasets/load.py", line 1189, in dataset_module_factory
    dataset_info = hf_api.dataset_info(
  File "/home/slesage/hf/datasets-preview-backend/.venv/lib/python3.9/site-packages/huggingface_hub/hf_api.py", line 947, in dataset_info
    r.raise_for_status()
  File "/home/slesage/hf/datasets-preview-backend/.venv/lib/python3.9/site-packages/requests/models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://huggingface.co/api/datasets/facebook/winoground?full=true
```

**Comment by odellus** [comment] 2022-04-12 14:59
Using your command to replicate and changing `use_token` to `use_auth_token` fixes the problem I was seeing in #4149.

**Comment by SBrandeis** [comment] 2022-04-13 10:19
After investigation with @severo , we found a potential culprit: https://github.com/huggingface/datasets/blob/3cd0a009a43f9f174056d70bfa2ca32216181926/src/datasets/utils/streaming_download_manager.py#L610-L624

The streaming manager does not seem to pass `use_auth_token` to `fsspec` when streaming and not iterating content of a zip archive

cc @albertvillanova @lhoestq

**Comment by lhoestq** [comment] 2022-04-14 12:48
I was able to reproduce it on a private dataset, let me work on a fix

**Comment by ankeshanand** [comment] 2022-04-23 17:14
Hey @lhoestq, Thanks for working on a fix! Any plans to merge #4173 into master?

**Comment by lhoestq** [comment] 2022-04-27 10:38
Thanks for the heads up, I still need to fix some tests that are failing in the CI before merging ;)

**Comment by lhoestq** [comment] 2022-05-06 09:43
The fix has been merged, we'll do a new release soon, and update the dataset viewer

**Closed** 2022-06-21 16:43 UTC
Labels: dataset-viewer, dataset-viewer-gated
