### ISSUE TITLE
Emotion dataset cannot be downloaded

### ISSUE THREAD

**Issue by cbarond** [huggingface/datasets#5342] opened 2022-12-08 19:07 UTC
### Describe the bug

The emotion dataset gives a FileNotFoundError. The full error is: `FileNotFoundError: Couldn't find file at https://www.dropbox.com/s/1pzkadrvffbqw6o/train.txt?dl=1`.

It was working yesterday (December 7, 2022), but stopped working today (December 8, 2022).

### Steps to reproduce the bug

```python
from datasets import load_dataset
dataset = load_dataset("emotion")
```

### Expected behavior

The dataset should load properly.

### Environment info

- `datasets` version: 2.7.1
- Platform: Windows-10-10.0.19045-SP0
- Python version: 3.9.13
- PyArrow version: 10.0.1
- Pandas version: 1.5.1

**Comment by alvarobartt** [comment] 2022-12-09 10:35
Hi @cbarond there's already an open issue at https://github.com/dair-ai/emotion_dataset/issues/5, as the data seems to be missing now, so check that issue instead 👍🏻

**Comment by albertvillanova** [comment] 2022-12-09 10:45
Thanks @cbarond for reporting and @alvarobartt for pointing to the issue we opened in the author's repo.

Indeed, this issue was first raised in the "emotion" dataset Community tab: https://huggingface.co/datasets/emotion/discussions/3

I'm closing this issue and leave the issue above for the subsequent updates.

Duplicate of: https://huggingface.co/datasets/emotion/discussions/3

**Closed** 2022-12-09 10:46 UTC
Labels: duplicate

**Comment by honeyimholm** [comment] 2022-12-09 16:41
try using "SetFit/emotion" instead

**Comment by arturosizes** [comment] 2022-12-09 19:11
> try using "SetFit/emotion" instead

I' replaced "emotion" with "SetFit/Emotion", but the code is getting stuck at

`emotions = load_dataset("SetFit/emotion")`

I pause execution using the debugger, and it takes me to filelock.py:226

`with self._thread_lock:`

Do you know a way to get past this issue?

**Comment by tansaku** [comment] 2022-12-23 10:56
thanks @honeyimholm - worked for me

**Comment by albertvillanova** [comment] 2023-01-02 12:05
The dataset loading script has been fixed: https://huggingface.co/datasets/emotion/discussions/4

**Comment by pnugues** [comment] 2023-02-23 10:29
Collecting the datasets with the statements:
``from datasets import list_datasets``
``all_datasets = list_datasets()``
from the notebook fails to find an ``emotion`` dataset. Running the statement:
``[item for item in all_datasets if 'emotion' in item][:5]``
here are the first items of the list I obtain:
``['dair-ai/emotion',
 'go_emotions',
 'Mansooreh/sharif-emotional-speech-dataset',
 'Pyjay/emotion_nl',
 'SetFit/emotion']``
and no ``emotion``.
