### ISSUE TITLE
HuggingFace website is incorrectly reporting that my datasets are pickled

### ISSUE THREAD

**Issue by ProGamerGov** [huggingface/datasets#5222] opened 2022-11-09 16:41 UTC
### Describe the bug

HuggingFace is incorrectly reporting that my datasets are pickled. They are not picked, they are simple ZIP files containing PNG images.

Hopefully this is the right location to report this bug.

### Steps to reproduce the bug

Inspect my dataset respository here: https://huggingface.co/datasets/ProGamerGov/StableDiffusion-v1-5-Regularization-Images

### Expected behavior

They should not be reported as being pickled.

### Environment info

N/A

**Comment by lhoestq** [comment] 2022-11-09 16:58
cc @McPatate maybe you know what's happening ?

**Comment by McPatate** [comment] 2022-11-09 17:44
Yes I think I know what is happening. We check in zips for pickles, and the UI must display the pickle jar when a scan has an associated list of imports, even when empty.
I'll fix ASAP !

**Comment by McPatate** [comment] 2022-11-09 18:05
>  I'll fix ASAP !

Actually I'd rather leave it like that for now, as it indicates that we checked for pickles and nothing dangerous appeared :)

**Comment by McPatate** [comment] 2022-11-09 18:06
Closing the issue with the typical "feature not a bug" response 😄

**Closed by McPatate** 2022-11-09 18:06 UTC
