### ISSUE TITLE
reddit_tifu dataset: Checksums didn't match for dataset source files

### ISSUE THREAD

**Issue by XingxingZhang** [huggingface/datasets#3942] opened 2022-03-16 15:23 UTC
## Describe the bug
When loading the reddit_tifu dataset, it throws the exception "Checksums didn't match for dataset source files"

## Steps to reproduce the bug
```python
import datasets
from datasets import load_dataset

print(datasets.__version__)

# load_dataset('billsum')

load_dataset('reddit_tifu', 'short')
```

## Environment info

- `datasets` version: 1.17.0
- Platform: mac os
- Python version: Python 3.7.6
- PyArrow version: 3.0.0

**Comment by albertvillanova** [comment] 2022-03-16 15:39
Hi @XingxingZhang, 

We have already fixed this. You should update `datasets` version to at least 1.18.4:
```shel
pip install -U datasets
```

Duplicate of:
- #3773

**Closed by albertvillanova** 2022-03-16 15:39 UTC
Labels: bug, duplicate

**Comment by XingxingZhang** [comment] 2022-03-16 15:52
thanks @albertvillanova . by upgrading to 1.18.4 and using `load_dataset("...", download_mode="force_redownload")` fixed 
 the bug.

using the following as you suggested in another thread can also fixed the bug
```
pip install git+https://github.com/huggingface/datasets#egg=datasets
```

**Comment by albertvillanova** [comment] 2022-03-16 15:57
The latter solution (installing from GitHub) was proposed because the fix was not released yet. But last week we made the 1.18.4 release (with the patch), so no longer necessary to install from GitHub.

You can now install from PyPI, as usual:
```shell
pip install -U datasets
```
