### ISSUE TITLE
Filtering on an empty dataset returns a corrupted dataset.

### ISSUE THREAD

**Issue by gabegma** [huggingface/datasets#5085] opened 2022-10-06 18:18 UTC
## Describe the bug
When filtering a dataset twice, where the first result is an empty dataset, the second dataset seems corrupted.

## Steps to reproduce the bug
```python
  datasets = load_dataset("glue", "sst2")
  dataset_split = datasets['validation']
  ds_filter_1 = dataset_split.filter(lambda x: False)  # Some filtering condition that leads to an empty dataset
  assert ds_filter_1.num_rows == 0
  sentences = ds_filter_1['sentence']
  assert len(sentences) == 0
  ds_filter_2 = ds_filter_1.filter(lambda x: False)  # Some other filtering condition
  assert ds_filter_2.num_rows == 0
  assert 'sentence' in ds_filter_2.column_names
  sentences = ds_filter_2['sentence']
```

## Expected results
The last line should be returning an empty list, same as 4 lines above.

## Actual results
The last line currently raises `IndexError: index out of bounds`.

## Environment info

- `datasets` version: 2.5.2
- Platform: macOS-11.6.6-x86_64-i386-64bit
- Python version: 3.9.11
- PyArrow version: 7.0.0
- Pandas version: 1.4.1

**Comment by Mouhanedg56** [comment] 2022-10-06 22:20
It seems like #5043 fix (merged recently) is the root cause of such behaviour. When we empty indices mapping (because the dataset length equals to zero), we can no longer get column item: `ds_filter_2['sentence']` which uses
`ds_filter_1._indices.column(0)`

#self-assign

**Comment by Mouhanedg56** [comment] 2022-10-06 22:24
#self-assign

**Closed** 2022-10-07 18:40 UTC
Labels: bug, hacktoberfest

**Comment by gabegma** [comment] 2022-10-07 19:06
Thank you for solving this amazingly quickly!
