### ISSUE TITLE
Streaming not supported in Theivaprakasham/wildreceipt

### ISSUE THREAD

**Issue by NitishkKarra** [huggingface/datasets#4775] opened 2022-08-01 09:46 UTC

**Comment by albertvillanova** [comment] 2022-08-01 10:30
Thanks for reporting @NitishkKarra.

The root source of the issue is that streaming mode is not supported out-of-the-box for that dataset, because it contains a TAR file.

We have opened a discussion in the corresponding Hub dataset page, pointing out this issue: https://huggingface.co/datasets/Theivaprakasham/wildreceipt/discussions/1

I'm closing this issue here, so this discussion is transferred there instead.

**Closed by albertvillanova** 2022-08-01 10:30 UTC
Labels: streaming
