### ISSUE TITLE
Inconsistent documentation on map remove_columns

### ISSUE THREAD

**Issue by zhaowei-wang-nlp** [huggingface/datasets#5144] opened 2022-10-21 08:37 UTC
### Describe the bug

The page [process](https://huggingface.co/docs/datasets/process) says this about the parameter `remove_columns` of the function `map`:
When you remove a column, it is only removed after the example has been provided to the mapped function.

So it seems that the `remove_columns` parameter removes after the mapped functions.

However, another page, [the documentation of the function map](https://huggingface.co/docs/datasets/v2.6.1/en/package_reference/main_classes#datasets.Dataset.map.remove_columns) says:
Columns will be removed before updating the examples with the output of `function`, i.e. if `function` is adding columns with names in remove_columns, these columns will be kept.

So one page says "after the mapped function" and another says "before the mapped function."
Is there something wrong?

### Steps to reproduce the bug

Not about code.

### Expected behavior

consistent about the descriptions of the behavior of the parameter `remove_columns` in the function `map`.

### Environment info

datasets V2.6.0

**Comment by albertvillanova** [comment] 2022-10-24 06:40
Thanks for reporting, @zhaowei-wang-nlp.

You are right, the documentation is confusing on the behavior of `remove_columns`. We should better explain it.

**Comment by mariosasko** [comment] 2022-10-24 11:32
This is a duplicate of https://github.com/huggingface/datasets/issues/2343.

**Comment by albertvillanova** [comment] 2022-11-15 14:15
I'm closing this issue because as @mariosasko pointed out, it is a duplicate of:
- #2343

**Closed by albertvillanova** 2022-11-15 14:15 UTC
Labels: documentation, duplicate, good first issue, hacktoberfest
