### ISSUE TITLE
Support Video 

### ISSUE THREAD

**Issue by yuvalkirstain** [huggingface/datasets#6560] opened 2024-01-04 13:10 UTC
### Feature request

HF datasets are awesome in supporting text and images. Will be great to see such a support in videos :) 

### Motivation

Video generation :) 

### Your contribution

Will probably be limited to raising this feature request ;)

**Comment by severo** [comment] 2024-08-23 09:51
duplicate of #5225

**Closed by severo** 2024-08-23 09:51 UTC
Labels: duplicate, enhancement
