### ISSUE TITLE
Support cloud storage for loading datasets

### ISSUE THREAD

**Issue by eli-osherovich** [huggingface/datasets#5771] opened 2023-04-19 12:43 UTC
### Feature request

It seems that the the current implementation supports cloud storage only for `load_from_disk`. It would be nice if a similar functionality existed in `load_dataset`.

### Motivation

Motivation is pretty clear -- let users work with datasets located in the cloud. 

### Your contribution

I can help implementing this.

**Comment by mariosasko** [comment] 2023-04-20 14:08
A duplicate of https://github.com/huggingface/datasets/issues/5281

**Closed** 2023-05-07 17:47 UTC
Labels: duplicate, enhancement
