### ISSUE TITLE
Why split slicing doesn't behave like list slicing ?

### ISSUE THREAD

**Issue by astariul** [huggingface/datasets#5875] opened 2023-05-19 07:21 UTC
### Describe the bug

If I want to get the first 10 samples of my dataset, I can do :

```
ds = datasets.load_dataset('mnist', split='train[:10]')
```

But if I exceed the number of samples in the dataset, an exception is raised : 

```
ds = datasets.load_dataset('mnist', split='train[:999999999]')
```

> ValueError: Requested slice [:999999999] incompatible with 60000 examples.

### Steps to reproduce the bug

```
ds = datasets.load_dataset('mnist', split='train[:999999999]')
```

### Expected behavior

I would expect it to behave like python lists (no exception raised, the whole list is kept) : 

```
d = list(range(1000))[:999999]
print(len(d))  # > 1000
```

### Environment info

- `datasets` version: 2.9.0
- Platform: macOS-12.6-arm64-arm-64bit
- Python version: 3.9.12
- PyArrow version: 11.0.0
- Pandas version: 1.5.3

**Comment by mariosasko** [comment] 2023-05-23 16:02
A duplicate of https://github.com/huggingface/datasets/issues/1774

**Closed** 2024-01-31 15:54 UTC
Labels: duplicate
