### ISSUE TITLE
disaster_response_messages unavailable

### ISSUE THREAD

**Issue by sacdallago** [huggingface/datasets#3416] opened 2021-12-10 13:49 UTC
## Dataset viewer issue for '* disaster_response_messages*'

**Link:** https://huggingface.co/datasets/disaster_response_messages

Dataset unavailable. Link dead: https://datasets.appen.com/appen_datasets/disaster_response_data/disaster_response_messages_training.csv

Am I the one who added this dataset ?No

**Comment by mariosasko** [comment] 2021-12-13 11:19
Hi, thanks for reporting! This is a duplicate of https://github.com/huggingface/datasets/issues/3240. We are working on a fix.

**Closed** 2021-12-14 14:38 UTC
Labels: dataset-viewer
